# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dogacekici.github.io/
title: Doğaç Ekici
email: dogac.ekici@paketmutfak.com.tr
author: Doğaç Ekici
description: > Doğaç Ekici's personal site features projects in AI, game development, and 3D art. Learn about his role at Paket Mutfak as a Software Crafter and read his articles on AI and society from Fikir Gazetesi.
copyright: ''
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/DogacEkici
  - title: linkedin
    url: https://www.linkedin.com/in/dogacekici
